//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios'
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  CancelToken,
} from 'axios'

export interface ICategoriesClient {
  getAll(cancelToken?: CancelToken): Promise<CategoryResponse[]>
}

export class CategoriesClient implements ICategoriesClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? 'http://localhost:5102'
  }

  getAll(cancelToken?: CancelToken): Promise<CategoryResponse[]> {
    let url_ = this.baseUrl + '/api/Categories'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAll(_response)
      })
  }

  protected processGetAll(
    response: AxiosResponse,
  ): Promise<CategoryResponse[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<CategoryResponse[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<CategoryResponse[]>(null as any)
  }
}

export interface IDishesClient {
  getAll(
    search: string | null | undefined,
    categoryId: string | null | undefined,
    sortBy: string | undefined,
    cancelToken?: CancelToken,
  ): Promise<DishResponse[]>
  create(
    req: CreateDishRequest,
    cancelToken?: CancelToken,
  ): Promise<DishResponse>
  getById(id: string, cancelToken?: CancelToken): Promise<DishResponse>
  delete(id: string, cancelToken?: CancelToken): Promise<FileResponse>
  getRanking(cancelToken?: CancelToken): Promise<DishResponse[]>
}

export class DishesClient implements IDishesClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? 'http://localhost:5102'
  }

  getAll(
    search: string | null | undefined,
    categoryId: string | null | undefined,
    sortBy: string | undefined,
    cancelToken?: CancelToken,
  ): Promise<DishResponse[]> {
    let url_ = this.baseUrl + '/api/Dishes?'
    if (search !== undefined && search !== null)
      url_ += 'search=' + encodeURIComponent('' + search) + '&'
    if (categoryId !== undefined && categoryId !== null)
      url_ += 'categoryId=' + encodeURIComponent('' + categoryId) + '&'
    if (sortBy === null)
      throw new globalThis.Error("The parameter 'sortBy' cannot be null.")
    else if (sortBy !== undefined)
      url_ += 'sortBy=' + encodeURIComponent('' + sortBy) + '&'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAll(_response)
      })
  }

  protected processGetAll(response: AxiosResponse): Promise<DishResponse[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<DishResponse[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<DishResponse[]>(null as any)
  }

  create(
    req: CreateDishRequest,
    cancelToken?: CancelToken,
  ): Promise<DishResponse> {
    let url_ = this.baseUrl + '/api/Dishes'
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(req)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCreate(_response)
      })
  }

  protected processCreate(response: AxiosResponse): Promise<DishResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<DishResponse>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<DishResponse>(null as any)
  }

  getById(id: string, cancelToken?: CancelToken): Promise<DishResponse> {
    let url_ = this.baseUrl + '/api/Dishes/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetById(_response)
      })
  }

  protected processGetById(response: AxiosResponse): Promise<DishResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<DishResponse>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<DishResponse>(null as any)
  }

  delete(id: string, cancelToken?: CancelToken): Promise<FileResponse> {
    let url_ = this.baseUrl + '/api/Dishes/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      responseType: 'blob',
      method: 'DELETE',
      url: url_,
      headers: {
        Accept: 'application/octet-stream',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDelete(_response)
      })
  }

  protected processDelete(response: AxiosResponse): Promise<FileResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers
        ? response.headers['content-disposition']
        : undefined
      let fileNameMatch = contentDisposition
        ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(
            contentDisposition,
          )
        : undefined
      let fileName =
        fileNameMatch && fileNameMatch.length > 1
          ? fileNameMatch[3] || fileNameMatch[2]
          : undefined
      if (fileName) {
        fileName = decodeURIComponent(fileName)
      } else {
        fileNameMatch = contentDisposition
          ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition)
          : undefined
        fileName =
          fileNameMatch && fileNameMatch.length > 1
            ? fileNameMatch[1]
            : undefined
      }
      return Promise.resolve({
        fileName: fileName,
        status: status,
        data: new Blob([response.data], {
          type: response.headers['content-type'],
        }),
        headers: _headers,
      })
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<FileResponse>(null as any)
  }

  getRanking(cancelToken?: CancelToken): Promise<DishResponse[]> {
    let url_ = this.baseUrl + '/api/Dishes/ranking'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetRanking(_response)
      })
  }

  protected processGetRanking(
    response: AxiosResponse,
  ): Promise<DishResponse[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<DishResponse[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<DishResponse[]>(null as any)
  }
}

export interface IReviewsClient {
  getAll(cancelToken?: CancelToken): Promise<ReviewResponse[]>
  create(
    req: CreateReviewRequest,
    cancelToken?: CancelToken,
  ): Promise<ReviewResponse>
  getById(id: string, cancelToken?: CancelToken): Promise<ReviewResponse>
  delete(id: string, cancelToken?: CancelToken): Promise<FileResponse>
  getByDish(
    dishId: string,
    cancelToken?: CancelToken,
  ): Promise<ReviewResponse[]>
  updatePhoto(
    id: string,
    photoUrl: string,
    cancelToken?: CancelToken,
  ): Promise<FileResponse>
}

export class ReviewsClient implements IReviewsClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? 'http://localhost:5102'
  }

  getAll(cancelToken?: CancelToken): Promise<ReviewResponse[]> {
    let url_ = this.baseUrl + '/api/Reviews'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAll(_response)
      })
  }

  protected processGetAll(response: AxiosResponse): Promise<ReviewResponse[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<ReviewResponse[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<ReviewResponse[]>(null as any)
  }

  create(
    req: CreateReviewRequest,
    cancelToken?: CancelToken,
  ): Promise<ReviewResponse> {
    let url_ = this.baseUrl + '/api/Reviews'
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(req)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCreate(_response)
      })
  }

  protected processCreate(response: AxiosResponse): Promise<ReviewResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<ReviewResponse>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<ReviewResponse>(null as any)
  }

  getById(id: string, cancelToken?: CancelToken): Promise<ReviewResponse> {
    let url_ = this.baseUrl + '/api/Reviews/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetById(_response)
      })
  }

  protected processGetById(response: AxiosResponse): Promise<ReviewResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<ReviewResponse>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<ReviewResponse>(null as any)
  }

  delete(id: string, cancelToken?: CancelToken): Promise<FileResponse> {
    let url_ = this.baseUrl + '/api/Reviews/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      responseType: 'blob',
      method: 'DELETE',
      url: url_,
      headers: {
        Accept: 'application/octet-stream',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDelete(_response)
      })
  }

  protected processDelete(response: AxiosResponse): Promise<FileResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers
        ? response.headers['content-disposition']
        : undefined
      let fileNameMatch = contentDisposition
        ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(
            contentDisposition,
          )
        : undefined
      let fileName =
        fileNameMatch && fileNameMatch.length > 1
          ? fileNameMatch[3] || fileNameMatch[2]
          : undefined
      if (fileName) {
        fileName = decodeURIComponent(fileName)
      } else {
        fileNameMatch = contentDisposition
          ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition)
          : undefined
        fileName =
          fileNameMatch && fileNameMatch.length > 1
            ? fileNameMatch[1]
            : undefined
      }
      return Promise.resolve({
        fileName: fileName,
        status: status,
        data: new Blob([response.data], {
          type: response.headers['content-type'],
        }),
        headers: _headers,
      })
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<FileResponse>(null as any)
  }

  getByDish(
    dishId: string,
    cancelToken?: CancelToken,
  ): Promise<ReviewResponse[]> {
    let url_ = this.baseUrl + '/api/Reviews/dish/{dishId}'
    if (dishId === undefined || dishId === null)
      throw new globalThis.Error("The parameter 'dishId' must be defined.")
    url_ = url_.replace('{dishId}', encodeURIComponent('' + dishId))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetByDish(_response)
      })
  }

  protected processGetByDish(
    response: AxiosResponse,
  ): Promise<ReviewResponse[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<ReviewResponse[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<ReviewResponse[]>(null as any)
  }

  updatePhoto(
    id: string,
    photoUrl: string,
    cancelToken?: CancelToken,
  ): Promise<FileResponse> {
    let url_ = this.baseUrl + '/api/Reviews/{id}/photo'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(photoUrl)

    let options_: AxiosRequestConfig = {
      data: content_,
      responseType: 'blob',
      method: 'PATCH',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/octet-stream',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processUpdatePhoto(_response)
      })
  }

  protected processUpdatePhoto(response: AxiosResponse): Promise<FileResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers
        ? response.headers['content-disposition']
        : undefined
      let fileNameMatch = contentDisposition
        ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(
            contentDisposition,
          )
        : undefined
      let fileName =
        fileNameMatch && fileNameMatch.length > 1
          ? fileNameMatch[3] || fileNameMatch[2]
          : undefined
      if (fileName) {
        fileName = decodeURIComponent(fileName)
      } else {
        fileNameMatch = contentDisposition
          ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition)
          : undefined
        fileName =
          fileNameMatch && fileNameMatch.length > 1
            ? fileNameMatch[1]
            : undefined
      }
      return Promise.resolve({
        fileName: fileName,
        status: status,
        data: new Blob([response.data], {
          type: response.headers['content-type'],
        }),
        headers: _headers,
      })
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<FileResponse>(null as any)
  }
}

export interface IUploadClient {
  uploadPhoto(
    file: FileParameter | null | undefined,
    cancelToken?: CancelToken,
  ): Promise<FileResponse>
}

export class UploadClient implements IUploadClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? 'http://localhost:5102'
  }

  uploadPhoto(
    file: FileParameter | null | undefined,
    cancelToken?: CancelToken,
  ): Promise<FileResponse> {
    let url_ = this.baseUrl + '/api/Upload'
    url_ = url_.replace(/[?&]$/, '')

    const content_ = new FormData()
    if (file !== null && file !== undefined)
      content_.append('file', file.data, file.fileName ? file.fileName : 'file')

    let options_: AxiosRequestConfig = {
      data: content_,
      responseType: 'blob',
      method: 'POST',
      url: url_,
      headers: {
        Accept: 'application/octet-stream',
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processUploadPhoto(_response)
      })
  }

  protected processUploadPhoto(response: AxiosResponse): Promise<FileResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers
        ? response.headers['content-disposition']
        : undefined
      let fileNameMatch = contentDisposition
        ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(
            contentDisposition,
          )
        : undefined
      let fileName =
        fileNameMatch && fileNameMatch.length > 1
          ? fileNameMatch[3] || fileNameMatch[2]
          : undefined
      if (fileName) {
        fileName = decodeURIComponent(fileName)
      } else {
        fileNameMatch = contentDisposition
          ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition)
          : undefined
        fileName =
          fileNameMatch && fileNameMatch.length > 1
            ? fileNameMatch[1]
            : undefined
      }
      return Promise.resolve({
        fileName: fileName,
        status: status,
        data: new Blob([response.data], {
          type: response.headers['content-type'],
        }),
        headers: _headers,
      })
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      )
    }
    return Promise.resolve<FileResponse>(null as any)
  }
}

export interface CategoryResponse {
  id?: string
  name?: string
  cuisine?: string
}

export interface DishResponse {
  id?: string
  name?: string
  category?: string | undefined
  cuisine?: string | undefined
  avgRating?: number
  reviewCount?: number
  createdAt?: string
}

export interface CreateDishRequest {
  name?: string
  categoryId?: string | undefined
}

export interface ReviewResponse {
  id?: string
  dishId?: string
  dishName?: string
  category?: string | undefined
  rating?: number
  reviewText?: string | undefined
  photoUrl?: string | undefined
  reviewedAt?: string
  createdAt?: string
}

export interface CreateReviewRequest {
  dishId?: string
  rating?: number
  reviewText?: string | undefined
  photoUrl?: string | undefined
}

export interface FileParameter {
  data: any
  fileName: string
}

export interface FileResponse {
  data: Blob
  status: number
  fileName?: string
  headers?: { [name: string]: any }
}

export class ApiException extends Error {
  override message: string
  status: number
  response: string
  headers: { [key: string]: any }
  result: any

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super()

    this.message = message
    this.status = status
    this.response = response
    this.headers = headers
    this.result = result
  }

  protected isApiException = true

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result
  else throw new ApiException(message, status, response, headers, null)
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true
}
